# docker-compose -f docker-compose.dev.yaml up --build
version: "3.8"
services:
  api:
    build:
      context: ./api
      target: development
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog:
    build:
      context: ./myblog
      target: development
    container_name: myblog_c
    depends_on:
      - api
    ports:
      - '3000:3000'
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./myblog:/app
      - /app/node_modules
    stdin_open: true

# version: '3.8'
# services:
#   client:
#     image: yousefalhindawi/myblog:v1
#     depends_on:
#       - server
#   server:
#     image: yousefalhindawi/api:v1
